apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: fintech
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: fintech-app
        image: 805703880776.dkr.ecr.us-east-1.amazonaws.com/fintech-app:IMAGE_TAG
